//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json;

namespace Atlassian.Jira.Remote
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://beans.soap.rpc.jira.atlassian.com")]
    public partial class RemoteComment
    {

        private string authorField;

        private string bodyField;

        private System.Nullable<System.DateTime> createdField;

        private string groupLevelField;

        private string idField;

        private string roleLevelField;

        private string updateAuthorField;

        private System.Nullable<System.DateTime> updatedField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        [JsonConverter(typeof(NestedValueJsonConverter), "name")]
        public string author
        {
            get
            {
                return this.authorField;
            }
            set
            {
                this.authorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> created
        {
            get
            {
                return this.createdField;
            }
            set
            {
                this.createdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string groupLevel
        {
            get
            {
                return this.groupLevelField;
            }
            set
            {
                this.groupLevelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string roleLevel
        {
            get
            {
                return this.roleLevelField;
            }
            set
            {
                this.roleLevelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        [JsonConverter(typeof(NestedValueJsonConverter), "name")]
        public string updateAuthor
        {
            get
            {
                return this.updateAuthorField;
            }
            set
            {
                this.updateAuthorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> updated
        {
            get
            {
                return this.updatedField;
            }
            set
            {
                this.updatedField = value;
            }
        }

        /// <remarks/>
        public System.Collections.Generic.IEnumerable<RemoteCommentProperty> properties { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://beans.soap.rpc.jira.atlassian.com")]
    public partial class RemoteWorklog
    {

        private string authorField;

        private string commentField;

        private System.Nullable<System.DateTime> createdField;

        private string groupLevelField;

        private string idField;

        private string roleLevelIdField;

        private System.Nullable<System.DateTime> startDateField;

        private string timeSpentField;

        private long timeSpentInSecondsField;

        private string updateAuthorField;

        private System.Nullable<System.DateTime> updatedField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        [JsonConverter(typeof(NestedValueJsonConverter), "name")]
        public string author
        {
            get
            {
                return this.authorField;
            }
            set
            {
                this.authorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> created
        {
            get
            {
                return this.createdField;
            }
            set
            {
                this.createdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string groupLevel
        {
            get
            {
                return this.groupLevelField;
            }
            set
            {
                this.groupLevelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string roleLevelId
        {
            get
            {
                return this.roleLevelIdField;
            }
            set
            {
                this.roleLevelIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        [JsonProperty("started")]
        [JsonConverter(typeof(DateFixupJsonConverter))]
        public System.Nullable<System.DateTime> startDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string timeSpent
        {
            get
            {
                return this.timeSpentField;
            }
            set
            {
                this.timeSpentField = value;
            }
        }

        /// <remarks/>
        [JsonIgnore]
        public long timeSpentInSeconds
        {
            get
            {
                return this.timeSpentInSecondsField;
            }
            set
            {
                this.timeSpentInSecondsField = value;
            }
        }

        [JsonProperty("timeSpentSeconds")]
        private long timeSpentInSecondsDeserializer
        {
            set
            {
                this.timeSpentInSeconds = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        [JsonConverter(typeof(NestedValueJsonConverter), "name")]
        public string updateAuthor
        {
            get
            {
                return this.updateAuthorField;
            }
            set
            {
                this.updateAuthorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> updated
        {
            get
            {
                return this.updatedField;
            }
            set
            {
                this.updatedField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://beans.soap.rpc.jira.atlassian.com")]
    public partial class RemoteAvatar
    {

        private string base64DataField;

        private string contentTypeField;

        private long idField;

        private string ownerField;

        private bool systemField;

        private string typeField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string base64Data
        {
            get
            {
                return this.base64DataField;
            }
            set
            {
                this.base64DataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string contentType
        {
            get
            {
                return this.contentTypeField;
            }
            set
            {
                this.contentTypeField = value;
            }
        }

        /// <remarks/>
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string owner
        {
            get
            {
                return this.ownerField;
            }
            set
            {
                this.ownerField = value;
            }
        }

        /// <remarks/>
        public bool system
        {
            get
            {
                return this.systemField;
            }
            set
            {
                this.systemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://beans.soap.rpc.jira.atlassian.com")]
    public partial class RemoteRoleActor
    {

        private string descriptorField;

        private string parameterField;

        private RemoteProjectRole projectRoleField;

        private string typeField;

        private RemoteUser[] usersField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string descriptor
        {
            get
            {
                return this.descriptorField;
            }
            set
            {
                this.descriptorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string parameter
        {
            get
            {
                return this.parameterField;
            }
            set
            {
                this.parameterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public RemoteProjectRole projectRole
        {
            get
            {
                return this.projectRoleField;
            }
            set
            {
                this.projectRoleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public RemoteUser[] users
        {
            get
            {
                return this.usersField;
            }
            set
            {
                this.usersField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://beans.soap.rpc.jira.atlassian.com")]
    public partial class RemoteProjectRole
    {

        private string descriptionField;

        private System.Nullable<long> idField;

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<long> id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://beans.soap.rpc.jira.atlassian.com")]
    public partial class RemoteUser : RemoteEntity
    {

        private string emailField;

        private string fullnameField;

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string fullname
        {
            get
            {
                return this.fullnameField;
            }
            set
            {
                this.fullnameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteGroup))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteUser))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://beans.soap.rpc.jira.atlassian.com")]
    public partial class RemoteEntity
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://beans.soap.rpc.jira.atlassian.com")]
    public partial class RemoteGroup : RemoteEntity
    {

        private string nameField;

        private RemoteUser[] usersField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public RemoteUser[] users
        {
            get
            {
                return this.usersField;
            }
            set
            {
                this.usersField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteProjectRoleActors))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://beans.soap.rpc.jira.atlassian.com")]
    public partial class RemoteRoleActors
    {

        private RemoteProjectRole projectRoleField;

        private RemoteRoleActor[] roleActorsField;

        private RemoteUser[] usersField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public RemoteProjectRole projectRole
        {
            get
            {
                return this.projectRoleField;
            }
            set
            {
                this.projectRoleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public RemoteRoleActor[] roleActors
        {
            get
            {
                return this.roleActorsField;
            }
            set
            {
                this.roleActorsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public RemoteUser[] users
        {
            get
            {
                return this.usersField;
            }
            set
            {
                this.usersField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://beans.soap.rpc.jira.atlassian.com")]
    public partial class RemoteProjectRoleActors : RemoteRoleActors
    {

        private RemoteProject projectField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public RemoteProject project
        {
            get
            {
                return this.projectField;
            }
            set
            {
                this.projectField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://beans.soap.rpc.jira.atlassian.com")]
    public partial class RemoteProject : AbstractNamedRemoteEntity
    {

        private string descriptionField;

        private RemoteScheme issueSecuritySchemeField;

        private string keyField;

        private string leadField;

        private RemoteScheme notificationSchemeField;

        private RemotePermissionScheme permissionSchemeField;

        private string projectUrlField;

        private string urlField;

        public ProjectCategory projectCategory { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public RemoteScheme issueSecurityScheme
        {
            get
            {
                return this.issueSecuritySchemeField;
            }
            set
            {
                this.issueSecuritySchemeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        [JsonConverter(typeof(NestedValueJsonConverter), "name")]
        public string lead
        {
            get
            {
                return this.leadField;
            }
            set
            {
                this.leadField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public RemoteScheme notificationScheme
        {
            get
            {
                return this.notificationSchemeField;
            }
            set
            {
                this.notificationSchemeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public RemotePermissionScheme permissionScheme
        {
            get
            {
                return this.permissionSchemeField;
            }
            set
            {
                this.permissionSchemeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string projectUrl
        {
            get
            {
                return this.projectUrlField;
            }
            set
            {
                this.projectUrlField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemotePermissionScheme))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://beans.soap.rpc.jira.atlassian.com")]
    public partial class RemoteScheme
    {

        private string descriptionField;

        private System.Nullable<long> idField;

        private string nameField;

        private string typeField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<long> id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://beans.soap.rpc.jira.atlassian.com")]
    public partial class RemotePermissionScheme : RemoteScheme
    {

        private RemotePermissionMapping[] permissionMappingsField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public RemotePermissionMapping[] permissionMappings
        {
            get
            {
                return this.permissionMappingsField;
            }
            set
            {
                this.permissionMappingsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://beans.soap.rpc.jira.atlassian.com")]
    public partial class RemotePermissionMapping
    {

        private RemotePermission permissionField;

        private RemoteEntity[] remoteEntitiesField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public RemotePermission permission
        {
            get
            {
                return this.permissionField;
            }
            set
            {
                this.permissionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public RemoteEntity[] remoteEntities
        {
            get
            {
                return this.remoteEntitiesField;
            }
            set
            {
                this.remoteEntitiesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://beans.soap.rpc.jira.atlassian.com")]
    public partial class RemotePermission
    {

        private string nameField;

        private System.Nullable<long> permissionField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<long> permission
        {
            get
            {
                return this.permissionField;
            }
            set
            {
                this.permissionField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteSecurityLevel))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteFilter))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteField))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteProject))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(AbstractRemoteConstant))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteStatus))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteResolution))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemotePriority))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteIssueType))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteNamedObject))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteComponent))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteVersion))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://beans.soap.rpc.jira.atlassian.com")]
    public abstract partial class AbstractNamedRemoteEntity : AbstractRemoteEntity
    {

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteAttachment))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteIssue))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(AbstractNamedRemoteEntity))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteSecurityLevel))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteFilter))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteField))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteProject))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(AbstractRemoteConstant))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteStatus))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteResolution))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemotePriority))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteIssueType))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteNamedObject))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteComponent))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteVersion))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://beans.soap.rpc.jira.atlassian.com")]
    public abstract partial class AbstractRemoteEntity
    {

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://beans.soap.rpc.jira.atlassian.com")]
    public partial class RemoteAttachment : AbstractRemoteEntity
    {

        private string authorField;

        private System.Nullable<System.DateTime> createdField;

        private string filenameField;

        private System.Nullable<long> filesizeField;

        private string mimetypeField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        [JsonConverter(typeof(NestedValueJsonConverter), "name")]
        public string author
        {
            get
            {
                return this.authorField;
            }
            set
            {
                this.authorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> created
        {
            get
            {
                return this.createdField;
            }
            set
            {
                this.createdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string filename
        {
            get
            {
                return this.filenameField;
            }
            set
            {
                this.filenameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<long> filesize
        {
            get
            {
                return this.filesizeField;
            }
            set
            {
                this.filesizeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string mimetype
        {
            get
            {
                return this.mimetypeField;
            }
            set
            {
                this.mimetypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://beans.soap.rpc.jira.atlassian.com")]
    public partial class RemoteIssue : AbstractRemoteEntity
    {

        private RemoteVersion[] affectsVersionsField;

        private string assigneeField;

        private string[] attachmentNamesField;

        private RemoteComponent[] componentsField;

        private System.Nullable<System.DateTime> createdField;

        private RemoteCustomFieldValue[] customFieldValuesField;

        private string descriptionField;

        private System.Nullable<System.DateTime> duedateField;

        private string environmentField;

        private RemoteVersion[] fixVersionsField;

        private string keyField;

        private string projectField;

        private string reporterField;

        private string summaryField;

        private System.Nullable<System.DateTime> updatedField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        [JsonProperty("versions")]
        public RemoteVersion[] affectsVersions
        {
            get
            {
                return this.affectsVersionsField;
            }
            set
            {
                this.affectsVersionsField = value;
            }
        }

        [System.Xml.Serialization.SoapIgnore]
        [JsonProperty("parent")]
        [JsonConverter(typeof(NestedValueJsonConverter), "key")]
        public string parentKey { get; set; }

        [System.Xml.Serialization.SoapIgnore]
        [JsonProperty("resolutiondate")]
        public System.Nullable<System.DateTime> resolutionDateReadOnly { get; set; }

        [System.Xml.Serialization.SoapIgnore]
        [JsonProperty("labels")]
        public string[] labels { get; set; }

        [JsonProperty("security")]
        public IssueSecurityLevel securityLevelReadOnly { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        [JsonConverter(typeof(NestedValueJsonConverter), "name")]
        public string assignee
        {
            get
            {
                return this.assigneeField;
            }
            set
            {
                this.assigneeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string[] attachmentNames
        {
            get
            {
                return this.attachmentNamesField;
            }
            set
            {
                this.attachmentNamesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public RemoteComponent[] components
        {
            get
            {
                return this.componentsField;
            }
            set
            {
                this.componentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> created
        {
            get
            {
                return this.createdField;
            }
            set
            {
                this.createdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        [JsonIgnore]
        public RemoteCustomFieldValue[] customFieldValues
        {
            get
            {
                return this.customFieldValuesField;
            }
            set
            {
                this.customFieldValuesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> duedate
        {
            get
            {
                return this.duedateField;
            }
            set
            {
                this.duedateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string environment
        {
            get
            {
                return this.environmentField;
            }
            set
            {
                this.environmentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public RemoteVersion[] fixVersions
        {
            get
            {
                return this.fixVersionsField;
            }
            set
            {
                this.fixVersionsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }       

        [JsonProperty("priority")]
        public RemotePriority priority { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        [JsonConverter(typeof(NestedValueJsonConverter), "key")]
        public string project
        {
            get
            {
                return this.projectField;
            }
            set
            {
                this.projectField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        [JsonConverter(typeof(NestedValueJsonConverter), "name")]
        public string reporter
        {
            get
            {
                return this.reporterField;
            }
            set
            {
                this.reporterField = value;
            }
        }


        public RemoteResolution resolution { get; set; }

        public RemoteStatus status { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string summary
        {
            get
            {
                return this.summaryField;
            }
            set
            {
                this.summaryField = value;
            }
        }

        [JsonProperty("issuetype")]
        public RemoteIssueType type { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> updated
        {
            get
            {
                return this.updatedField;
            }
            set
            {
                this.updatedField = value;
            }
        }

        [JsonProperty("votes")]
        public RemoteVotes votesData { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://beans.soap.rpc.jira.atlassian.com")]
    public partial class RemoteVersion : AbstractNamedRemoteEntity
    {

        private bool archivedField;

        private System.Nullable<System.DateTime> startDateField;

        private System.Nullable<System.DateTime> releaseDateField;

        private bool releasedField;

        private System.Nullable<long> sequenceField;

        private string descriptionField;

        [JsonProperty("projectId")]
        public string ProjectId { get; set; }

        [JsonProperty("project")]
        public string ProjectKey { get; set; }

        /// <remarks/>
        public bool archived
        {
            get
            {
                return this.archivedField;
            }
            set
            {
                this.archivedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> startDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> releaseDate
        {
            get
            {
                return this.releaseDateField;
            }
            set
            {
                this.releaseDateField = value;
            }
        }

        /// <remarks/>
        public bool released
        {
            get
            {
                return this.releasedField;
            }
            set
            {
                this.releasedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<long> sequence
        {
            get
            {
                return this.sequenceField;
            }
            set
            {
                this.sequenceField = value;
            }
        }

        [System.Xml.Serialization.SoapIgnore]
        /// <remarks/>
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://beans.soap.rpc.jira.atlassian.com")]
    public partial class RemoteComponent : AbstractNamedRemoteEntity
    {
        [JsonProperty("project")]
        public string ProjectKey { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://beans.soap.rpc.jira.atlassian.com")]
    public partial class RemoteCustomFieldValue
    {

        private string customfieldIdField;

        private string keyField;

        private string[] valuesField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string customfieldId
        {
            get
            {
                return this.customfieldIdField;
            }
            set
            {
                this.customfieldIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string[] values
        {
            get
            {
                return this.valuesField;
            }
            set
            {
                this.valuesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://beans.soap.rpc.jira.atlassian.com")]
    public partial class RemoteSecurityLevel : AbstractNamedRemoteEntity
    {

        private string descriptionField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://beans.soap.rpc.jira.atlassian.com")]
    public partial class RemoteFilter : AbstractNamedRemoteEntity
    {

        private string authorField;

        private string descriptionField;

        private string projectField;

        private string xmlField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string author
        {
            get
            {
                return this.authorField;
            }
            set
            {
                this.authorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string project
        {
            get
            {
                return this.projectField;
            }
            set
            {
                this.projectField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string xml
        {
            get
            {
                return this.xmlField;
            }
            set
            {
                this.xmlField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://beans.soap.rpc.jira.atlassian.com")]
    public partial class RemoteField : AbstractNamedRemoteEntity
    {
        [System.Xml.Serialization.SoapIgnore]
        [JsonProperty("custom")]
        public bool IsCustomField { get; set; }

        [System.Xml.Serialization.SoapIgnore]
        [JsonProperty("schema")]
        [JsonConverter(typeof(NestedValueJsonConverter), "custom")]
        public string CustomFieldType { get; set; }
    }

    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteStatus))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteResolution))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemotePriority))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteIssueType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://beans.soap.rpc.jira.atlassian.com")]
    public abstract partial class AbstractRemoteConstant : AbstractNamedRemoteEntity
    {
        public string description { get; set; }
        public string iconUrl { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://beans.soap.rpc.jira.atlassian.com")]
    public partial class RemoteStatus : AbstractRemoteConstant
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://beans.soap.rpc.jira.atlassian.com")]
    public partial class RemoteResolution : AbstractRemoteConstant
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://beans.soap.rpc.jira.atlassian.com")]
    public partial class RemotePriority : AbstractRemoteConstant
    {

        private string colorField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string color
        {
            get
            {
                return this.colorField;
            }
            set
            {
                this.colorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://beans.soap.rpc.jira.atlassian.com")]
    public partial class RemoteIssueType : AbstractRemoteConstant
    {

        private bool subTaskField;

        /// <remarks/>
        [JsonIgnore]
        public bool subTask
        {
            get
            {
                return this.subTaskField;
            }
            set
            {
                this.subTaskField = value;
            }
        }

        [JsonProperty("subtask")]
        public bool subTaskDeserializer
        {
            set
            {
                this.subTask = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://beans.soap.rpc.jira.atlassian.com")]
    public partial class RemoteNamedObject : AbstractNamedRemoteEntity
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://beans.soap.rpc.jira.atlassian.com")]
    public partial class RemoteFieldValue
    {

        private string idField;

        private string[] valuesField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string[] values
        {
            get
            {
                return this.valuesField;
            }
            set
            {
                this.valuesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://beans.soap.rpc.jira.atlassian.com")]
    public partial class RemoteTimeInfo
    {

        private string serverTimeField;

        private string timeZoneIdField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string serverTime
        {
            get
            {
                return this.serverTimeField;
            }
            set
            {
                this.serverTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string timeZoneId
        {
            get
            {
                return this.timeZoneIdField;
            }
            set
            {
                this.timeZoneIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://beans.soap.rpc.jira.atlassian.com")]
    public partial class RemoteServerInfo
    {

        private string baseUrlField;

        private System.Nullable<System.DateTime> buildDateField;

        private string buildNumberField;

        private string editionField;

        private RemoteTimeInfo serverTimeField;

        private string versionField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string baseUrl
        {
            get
            {
                return this.baseUrlField;
            }
            set
            {
                this.baseUrlField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> buildDate
        {
            get
            {
                return this.buildDateField;
            }
            set
            {
                this.buildDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string buildNumber
        {
            get
            {
                return this.buildNumberField;
            }
            set
            {
                this.buildNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string edition
        {
            get
            {
                return this.editionField;
            }
            set
            {
                this.editionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public RemoteTimeInfo serverTime
        {
            get
            {
                return this.serverTimeField;
            }
            set
            {
                this.serverTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://beans.soap.rpc.jira.atlassian.com")]
    public partial class RemoteConfiguration
    {

        private bool allowAttachmentsField;

        private bool allowExternalUserManagmentField;

        private bool allowIssueLinkingField;

        private bool allowSubTasksField;

        private bool allowTimeTrackingField;

        private bool allowUnassignedIssuesField;

        private bool allowVotingField;

        private bool allowWatchingField;

        private int timeTrackingDaysPerWeekField;

        private int timeTrackingHoursPerDayField;

        /// <remarks/>
        public bool allowAttachments
        {
            get
            {
                return this.allowAttachmentsField;
            }
            set
            {
                this.allowAttachmentsField = value;
            }
        }

        /// <remarks/>
        public bool allowExternalUserManagment
        {
            get
            {
                return this.allowExternalUserManagmentField;
            }
            set
            {
                this.allowExternalUserManagmentField = value;
            }
        }

        /// <remarks/>
        public bool allowIssueLinking
        {
            get
            {
                return this.allowIssueLinkingField;
            }
            set
            {
                this.allowIssueLinkingField = value;
            }
        }

        /// <remarks/>
        public bool allowSubTasks
        {
            get
            {
                return this.allowSubTasksField;
            }
            set
            {
                this.allowSubTasksField = value;
            }
        }

        /// <remarks/>
        public bool allowTimeTracking
        {
            get
            {
                return this.allowTimeTrackingField;
            }
            set
            {
                this.allowTimeTrackingField = value;
            }
        }

        /// <remarks/>
        public bool allowUnassignedIssues
        {
            get
            {
                return this.allowUnassignedIssuesField;
            }
            set
            {
                this.allowUnassignedIssuesField = value;
            }
        }

        /// <remarks/>
        public bool allowVoting
        {
            get
            {
                return this.allowVotingField;
            }
            set
            {
                this.allowVotingField = value;
            }
        }

        /// <remarks/>
        public bool allowWatching
        {
            get
            {
                return this.allowWatchingField;
            }
            set
            {
                this.allowWatchingField = value;
            }
        }

        /// <remarks/>
        public int timeTrackingDaysPerWeek
        {
            get
            {
                return this.timeTrackingDaysPerWeekField;
            }
            set
            {
                this.timeTrackingDaysPerWeekField = value;
            }
        }

        /// <remarks/>
        public int timeTrackingHoursPerDay
        {
            get
            {
                return this.timeTrackingHoursPerDayField;
            }
            set
            {
                this.timeTrackingHoursPerDayField = value;
            }
        }
    }

    public partial class RemoteVotes
    {
        public long votes { get; set; }

        public bool hasVoted { get; set; }
    }

    public class RemoteCommentProperty
    {
        public string key { get; set; }
        public object value { get; set; }
    }
}